#!/bin/sh
set -u
set -e

# install scl repos, epel, python 37, and numpy for python37
yum install -y gcc openssl-devel bzip2-devel libffi-devel make \
    && cd /usr/src \
    && wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz \
    && tar xzf Python-3.7.4.tgz \
    && cd Python-3.7.4 \
    && ./configure --enable-optimizations \
    && make install \
    && rm /usr/src/Python-3.7.4.tgz
